name: chapter_aws
description: A modern messaging app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  http: ^1.1.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  http: ^1.1.0
  
  # AWS dependencies
  amplify_flutter: ^1.6.0
  amplify_auth_cognito: ^1.6.0
  amplify_api: ^1.6.0
  amplify_storage_s3: ^1.6.0
  amazon_chime_sdk_call: ^0.8.0
  provider: ^6.1.1  # For state management
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # You can add these later if needed
  # assets:
  #   - assets/images/
  #   - assets/gifs/

  # Fonts configuration
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700