import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_storage_s3/amplify_storage_s3.dart';
import 'package:flutter/material.dart';

class AwsConfig {
  static final AwsConfig _instance = AwsConfig._internal();
  
  factory AwsConfig() {
    return _instance;
  }
  
  AwsConfig._internal();
  
  bool _isConfigured = false;
  
  bool get isConfigured => _isConfigured;
  
  Future<void> configureAmplify() async {
    if (_isConfigured) return;
    
    try {
      // Add the following plugins
      final authPlugin = AmplifyAuthCognito();
      final apiPlugin = AmplifyAPI();
      final storagePlugin = AmplifyStorageS3();
      
      await Amplify.addPlugins([
        authPlugin,
        apiPlugin,
        storagePlugin,
      ]);
      
      // Load and configure Amplify using amplifyconfiguration.dart
      // This file will be generated by the Amplify CLI
      await Amplify.configure('''
      {
        "UserAgent": "aws-amplify-cli/2.0",
        "Version": "1.0",
        "auth": {
          "plugins": {
            "awsCognitoAuthPlugin": {
              "UserAgent": "aws-amplify/cli",
              "Version": "0.1.0",
              "IdentityManager": {
                "Default": {}
              },
              "CredentialsProvider": {
                "CognitoIdentity": {
                  "Default": {
                    "PoolId": "YOUR_IDENTITY_POOL_ID",
                    "Region": "YOUR_REGION"
                  }
                }
              },
              "CognitoUserPool": {
                "Default": {
                  "PoolId": "YOUR_USER_POOL_ID",
                  "AppClientId": "YOUR_APP_CLIENT_ID",
                  "Region": "YOUR_REGION"
                }
              }
            }
          }
        },
        "api": {
          "plugins": {
            "awsAPIPlugin": {
              "chapterApi": {
                "endpointType": "GraphQL",
                "endpoint": "YOUR_APPSYNC_ENDPOINT",
                "region": "YOUR_REGION",
                "authorizationType": "AMAZON_COGNITO_USER_POOLS"
              }
            }
          }
        },
        "storage": {
          "plugins": {
            "awsS3StoragePlugin": {
              "bucket": "YOUR_S3_BUCKET_NAME",
              "region": "YOUR_REGION",
              "defaultAccessLevel": "guest"
            }
          }
        }
      }
      ''');
      
      _isConfigured = true;
      debugPrint('Amplify configured successfully');
    } catch (e) {
      debugPrint('Error configuring Amplify: $e');
      rethrow;
    }
  }
}